### ISSUE TITLE
大佬，可不可以完善下录制跟保存，现在拍照选择滤镜没有效果，想要根据这个项目好好学习下

### ISSUE THREAD

**Issue by Uenchi** [githubhaohao/OpenGLCamera2#2]

**Comment by githubhaohao** [comment]
后面会搞下，现在在折腾 ffmpeg, 可以加我微信Byte-Flow

WU1208 <notifications@github.com> 于2020年9月9日周三 下午12:16写道：

**Comment by githubhaohao** [comment]
音视频录制已实现，移步项目：https://github.com/githubhaohao/LearnFFmpeg

**Comment by 2014gaokao** [comment]
+1，大佬麻烦完善下录制跟保存

**Comment by githubhaohao** [comment]
音视频录制已支持，请移步项目：https://github.com/githubhaohao/LearnFFmpeg

zhoucongcong ***@***.***> 于2021年6月20日周日 下午12:38写道：
